#!/bin/bash

SUPPORTED_JP="7.1, 7.0, 6.2.2, 6.2.1, 6.2, 6.1, 6.0, 5.1.6, 5.1.2, 5.0.2, 4.6.1"

JP_INPUT_VERSION="$1"
if [[ -z "${JP_INPUT_VERSION}" || "$1" == "-h" ]]; then
    JP_INPUT_VERSION="${SUPPORTED_JP%%,*}"
    if [[ -f "jetpack_version" ]]; then
        JP_INPUT_VERSION="$(cat jetpack_version)"
    fi
fi

if [[ $1 == "-h" ]]; then
    echo supported JetPack versions: ${SUPPORTED_JP}
	echo pre-selected/active: ${JP_INPUT_VERSION:-none}
    exit 0
fi

export JP_INPUT_VERSION
export JETPACK_VERSION="${JP_INPUT_VERSION}"
LICENSE=release
export ARCH=arm64
BUILD_SRCS="sources_${JP_INPUT_VERSION}"

function version_lt {
	IFS='.' read -r -a v1 <<< "$1"
	IFS='.' read -r -a v2 <<< "$2"
	for i in 0 1 2; do
		[[ v1[i] -lt v2[i] ]] && return 0
		[[ v1[i] -gt v2[i] ]] && return 1
	done
	return 1
}

echo "JetPack version ${JP_INPUT_VERSION}..."

if ! version_lt "$JP_INPUT_VERSION" 7.0; then
	case "${JP_INPUT_VERSION}" in
		7.1) REVISION=38.4;;
		7.0) REVISION=38.2;;
	esac
	KERNEL_DIR="kernel/kernel-noble-src"
	JETPACK_VERSION="7.x"
	L4T_VERSION=jetson_"${REVISION}"
elif ! version_lt "$JP_INPUT_VERSION" 6.0; then
	case "${JP_INPUT_VERSION}" in
		6.2.2) REVISION=36.5;;
		6.2.1) REVISION=36.4.4;;
		6.2) REVISION=36.4.3;;
		6.1) REVISION=36.4;;
		6.0) REVISION=36.3;;
	esac
	KERNEL_DIR="kernel/kernel-jammy-src"
	JETPACK_VERSION="6.x"
	L4T_VERSION=jetson_"${REVISION}"
elif ! version_lt "${JP_INPUT_VERSION}" 5.0; then
	case "${JP_INPUT_VERSION}" in
		5.1.6) REVISION=35.6.4;;
		5.1.2) REVISION=35.4.1;;
		5.0.2) REVISION=35.1
			LICENSE=Release;;
	esac
	KERNEL_DIR="kernel/kernel-5.10"
	JETPACK_VERSION="5.x"
	L4T_VERSION=jetson_"${REVISION}"
elif ! version_lt "${JP_INPUT_VERSION}" 4.0; then
	case "${JP_INPUT_VERSION}" in
		4.6.1) REVISION=32.7.1;;
	esac
	KERNEL_DIR="kernel/kernel-4.9"
	JETPACK_VERSION="4.x"
	L4T_VERSION="tegra-l4t-r${REVISION}"
	LICENSE=T186
fi
if [[ -z $REVISION ]]; then
	echo "Wrong JetPack version $JP_INPUT_VERSION! Supported version: ${SUPPORTED_JP}"
	exit 1
fi
echo "${JP_INPUT_VERSION}" > jetpack_version
