#!/bin/bash

SUPPORTED_JP="7.1, 7.0, 6.2.1, 6.2, 6.1, 6.0, 5.1.2, 5.0.2, 4.6.1"

if [[ $1 == "-h" ]]; then
    echo supported JetPack versions: ${SUPPORTED_JP}
    exit 0
fi

JP_INPUT_VERSION="$1"
if [[ -z "${JP_INPUT_VERSION}" ]]; then
    JP_INPUT_VERSION="${SUPPORTED_JP%%,*}"
    if [[ -f "jetpack_version" ]]; then
        JP_INPUT_VERSION="$(cat jetpack_version)"
    fi
fi

export JP_INPUT_VERSION
export JETPACK_VERSION="${JP_INPUT_VERSION}"
REVISION="35.1"
L4T_VERSION=jetson_"${REVISION}"
KERNEL_DIR="kernel/kernel-5.10"
LICENSE=release
export ARCH=arm64
BUILD_SRCS="sources_${JP_INPUT_VERSION}"

function version_lt {
    IFS='.' read -r -a v1 <<< "$1"
    IFS='.' read -r -a v2 <<< "$2"
    for i in 0 1 2; do
        [[ v1[i] -lt v2[i] ]] && return 0
        [[ v1[i] -gt v2[i] ]] && return 1
    done
    return 1
}

echo "JetPack version ${JP_INPUT_VERSION}..."
if [[ "$JETPACK_VERSION" =~ ^7\.[0-1]$ ]]; then
    if [[ $JETPACK_VERSION == "7.1" ]]; then
        REVISION="38.4"
    elif [[ $JETPACK_VERSION == "7.0" ]]; then
        REVISION="38.2"
    fi;
    KERNEL_DIR="kernel/kernel-noble-src"
    JETPACK_VERSION="7.x"
    L4T_VERSION=jetson_"${REVISION}"
elif [[ "$JETPACK_VERSION" =~ ^6\.[0-2](\.[0-9]+)?$ ]]; then
    if [[ $JETPACK_VERSION == "6.2.1" ]]; then
        REVISION="36.4.4"
    elif [[ $JETPACK_VERSION == "6.2" ]]; then
        REVISION="36.4.3"
    elif [[ $JETPACK_VERSION == "6.1" ]]; then
        REVISION="36.4"
    elif [[ $JETPACK_VERSION == "6.0" ]]; then
        REVISION="36.3"
    fi;
    KERNEL_DIR="kernel/kernel-jammy-src"
    JETPACK_VERSION="6.x"
    L4T_VERSION=jetson_"${REVISION}"
elif [[ "$JETPACK_VERSION" =~ ^5.[0-1].2$ ]]; then
    if [[ $JETPACK_VERSION == "5.1.2" ]]; then
        REVISION="35.4.1"
    elif [[ $JETPACK_VERSION == "5.0.2" ]]; then
        REVISION="35.1"
        LICENSE=Release
    fi
    KERNEL_DIR="kernel/kernel-5.10"
    JETPACK_VERSION="5.x"
    L4T_VERSION=jetson_"${REVISION}"
elif [[ $JETPACK_VERSION == "4.6.1" ]]; then
    KERNEL_DIR="kernel/kernel-4.9"
    REVISION="32.7.1"
    L4T_VERSION="tegra-l4t-r${REVISION}"
    LICENSE=T186
    JETPACK_VERSION="4.x"
else
    echo "Wrong JetPack version ($JETPACK_VERSION)! Supported version: ${SUPPORTED_JP}"
    exit 1
fi
echo "${JP_INPUT_VERSION}" > jetpack_version
