k:kernel/kernel-4.9:nv-tegra/linux-4.9.git:
k:kernel/nvgpu:nv-tegra/linux-nvgpu.git:
k:kernel/nvidia:nv-tegra/linux-nvidia.git:
k:hardware/nvidia/soc/t18x:nv-tegra/device/hardware/nvidia/soc/t18x.git:
k:hardware/nvidia/platform/tegra/common:nv-tegra/device/hardware/nvidia/platform/tegra/common.git:
k:hardware/nvidia/platform/t18x/common:nv-tegra/device/hardware/nvidia/platform/t18x/common.git:
k:hardware/nvidia/platform/t18x/quill:nv-tegra/device/hardware/nvidia/platform/t18x/quill.git:
k:hardware/nvidia/platform/t18x/lanai:nv-tegra/device/hardware/nvidia/platform/t18x/lanai.git:
k:hardware/nvidia/soc/t210:nv-tegra/device/hardware/nvidia/soc/t210.git:
k:hardware/nvidia/platform/t210/common:nv-tegra/device/hardware/nvidia/platform/t210/common.git:
k:hardware/nvidia/platform/t210/jetson:nv-tegra/device/hardware/nvidia/platform/t210/jetson.git:
k:hardware/nvidia/platform/t210/porg:nv-tegra/device/hardware/nvidia/platform/t210/porg.git:
k:hardware/nvidia/platform/t210/batuu/kernel-dts:nv-tegra/device/hardware/nvidia/platform/t210/batuu-dts.git:
k:hardware/nvidia/soc/t19x:nv-tegra/device/hardware/nvidia/soc/t19x.git:
k:hardware/nvidia/platform/t19x/common:nv-tegra/device/hardware/nvidia/platform/t19x/common.git:
k:hardware/nvidia/platform/t19x/galen/kernel-dts:nv-tegra/device/hardware/nvidia/platform/t19x/stardust-dts.git:
k:hardware/nvidia/platform/t19x/jakku/kernel-dts:nv-tegra/device/hardware/nvidia/platform/t19x/jakku-dts.git:
k:hardware/nvidia/platform/t19x/mccoy/kernel-dts:nv-tegra/device/hardware/nvidia/platform/t19x/mccoy-dts.git:
k:hardware/nvidia/platform/t19x/galen-industrial-dts/kernel-dts:nv-tegra/device/hardware/nvidia/platform/t19x/galen-industrial-dts.git:
k:hardware/nvidia/soc/tegra:nv-tegra/device/hardware/nvidia/soc/tegra.git:
